spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

client:
  open-ai:
    api-key: ${OPEN_AI_API_KEY}

  github:
    token: ${GITHUB_TOKEN}
    web-hook-secret: ${WEB_HOOK_SECRET}